import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { Bot, CheckCircle2, Copy, Loader2 } from "lucide-react";
import { useState } from "react";

export default function Telegram() {
  const organizations = trpc.organization.mine.useQuery();
  const organizationId = organizations.data?.[0]?.id;
  const [message, setMessage] = useState("");
  const [code, setCode] = useState<{ code: string; expiresAt: Date }>();
  const generate = trpc.telegram.linkCode.useMutation({ onSuccess: result => { setCode({ code: result.code, expiresAt: new Date(result.expiresAt) }); setMessage("Código gerado. Envie-o ao bot antes do vencimento."); }, onError: error => setMessage(error.message) });
  const webhookUrl = `${window.location.origin}/api/telegram/webhook`;
  const copyCode = async () => { if (code) { await navigator.clipboard?.writeText(`/vincular ${code.code}`); setMessage("Comando copiado."); } };
  return <DashboardLayout><div className="mx-auto w-full max-w-3xl space-y-6"><section className="border-b border-border/70 pb-6"><p className="text-sm font-medium uppercase tracking-[0.18em] text-primary">Integrações</p><h1 className="mt-2 text-2xl font-semibold sm:text-3xl">Bot Telegram</h1><p className="mt-2 text-sm text-muted-foreground sm:text-base">Vincule seu Telegram sem informar Chat ID manualmente.</p></section><Card><CardHeader><CardTitle className="flex items-center gap-2"><Bot className="h-5 w-5 text-primary" />Vinculação automática</CardTitle><CardDescription>Gere um código temporário, abra o bot TechVet e envie o comando exibido. O código é de uso único e expira em 15 minutos.</CardDescription></CardHeader><CardContent className="grid gap-4"><Button className="min-h-11 w-fit" disabled={!organizationId || generate.isPending} onClick={() => organizationId && generate.mutate({ organizationId })}>{generate.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <CheckCircle2 className="mr-2 h-4 w-4" />}Gerar código de vinculação</Button>{code ? <div className="grid gap-3 rounded-xl border border-primary/30 bg-primary/5 p-4"><p className="text-sm text-muted-foreground">Envie este comando ao bot:</p><code className="break-all text-lg font-semibold text-primary">/vincular {code.code}</code><p className="text-xs text-muted-foreground">Válido até {code.expiresAt.toLocaleString("pt-BR")}</p><Button type="button" variant="outline" className="min-h-11 w-fit" onClick={copyCode}><Copy className="mr-2 h-4 w-4" />Copiar comando</Button></div> : null}{message ? <p className="text-sm text-primary">{message}</p> : null}</CardContent></Card><Card><CardHeader><CardTitle>Webhook do bot</CardTitle><CardDescription>Endereço atualmente exibido para a publicação em uso.</CardDescription></CardHeader><CardContent><code className="block overflow-x-auto rounded-lg bg-muted p-3 text-xs">{webhookUrl}</code></CardContent></Card><Card><CardHeader><CardTitle>Comandos disponíveis</CardTitle></CardHeader><CardContent><pre className="overflow-x-auto whitespace-pre-wrap rounded-lg bg-muted p-4 text-sm leading-7">{`/vincular CODIGO\n/ajuda\n/paciente NOME DO PROPRIETÁRIO\n/resumo ID_DO_ANIMAL\n/atendimento ID_DO_ANIMAL TEXTO\n/observacao ID_DO_ANIMAL TEXTO\n/agendar ID_DO_ANIMAL 2026-09-20T14:00\n/pdf ID_DO_ANIMAL\n/sair`}</pre></CardContent></Card></div></DashboardLayout>;
}
